version: "3.8"
services:
  Candidate:
    container_name: account-service
    build: ./account-service
    ports:
      - "8083:8083"
    hostname: account
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888/

    image: "account-service"
    depends_on:
      - Eureka
    User:
      container_name: user-service
      build: ./user-service
      ports:
        - "8087:8087"
      hostname: users
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      image: "user-service"
      depends_on:
        - Eureka

    loan:
      container_name: loan-service
      build: ./loan-service
      ports:
        - "8085:8085"
      hostname: loan
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      image: "loan-service"
      depends_on:
        - Eureka

    Transaction:
      container_name: transaction-service
      build: ./transaction-service
      ports:
        - "8087:8087"
      hostname: transaction
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      image: "transaction-service"
      depends_on:
        - Eureka

    Auth:
      container_name: auth-service
      build: ./auth-service
      ports:
        - "8081:8081"
      hostname: authentification
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      image: "auth-service"
      depends_on:
        - Eureka

    Gateway:
      container_name: api-gateway
      build: ./api-gateway
      ports:
        - "8054:8054"
      hostname: api-gateway
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      image: "api-gateway"
      depends_on:
        - Eureka

    Eureka:
      container_name: eureka-server
      build: ./eureka-server
      ports:
        - "8761:8761"
      hostname: eureka-server
      image: "eureka-server"
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    configserver:
      container_name: configserver
      build: ./configserver
      ports:
        - "8888:8888"
      hostname: configserver
      image: "configserver"
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    Mongo:
        container_name: Mongo
        image: "mongo:5-focal"
        ports:
          - "27017:27017"
        hostname: mongodb
        depends_on:
          - "Eureka"
